"""
MultiViewer Well Log Viewer — Wells API Routes
WL-BUILD-001 scaffold

FastAPI route module for well-log viewer endpoints.

Architecture rules:
- Routes delegate to services and adapters. No business logic in route bodies.
- Routes convert service/adapter-raised NotImplementedError to HTTP 501.
- Each route expresses the full intended delegation chain.
  Services/adapters raise NotImplementedError for unimplemented steps;
  the route catches and converts. No route falls through silently.
- MSI adapter is the sole boundary for lifecycle and registration operations.
- Frontend fetches the well_multitrack_v1 viewer package from these routes.
- Routes do not parse LAS or own lifecycle state.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, HTTPException, status

from .msi_well_adapter import MsiWellAdapter
from .models import QaqcFinding, WellMultitrackV1
from .well_qaqc_service import WellQaqcService
from .well_viewer_package_service import WellViewerPackageService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/wells", tags=["wells"])

# Service instances — in a real application these would be injected via
# dependency injection (e.g. FastAPI Depends). Instantiated here as
# placeholders for the scaffold.
_msi_adapter = MsiWellAdapter()
_viewer_package_service = WellViewerPackageService()
_qaqc_service = WellQaqcService()


def _not_implemented_to_501(exc: NotImplementedError, detail_prefix: str) -> HTTPException:
    """
    Convert a service/adapter-raised NotImplementedError to HTTP 501.

    Routes call services; services raise NotImplementedError in scaffold state.
    Routes must not raise 501 directly — the 501 must originate from a
    failed service or adapter call.
    """
    logger.debug("Service not yet implemented: %s", exc)
    return HTTPException(
        status_code=status.HTTP_501_NOT_IMPLEMENTED,
        detail=f"{detail_prefix}: {exc}",
    )


# ---------------------------------------------------------------------------
# Viewer package endpoint
# ---------------------------------------------------------------------------


@router.get(
    "/{dataset_id}/representations/{representation_id}/viewer-package",
    response_model=WellMultitrackV1,
    summary="Fetch the well_multitrack_v1 viewer package for a representation.",
    description=(
        "Returns the backend-owned well_multitrack_v1 viewer package. "
        "The frontend must render this contract through the equinorWellLogAdapter. "
        "The ViDEx internal data shape must not become this contract."
    ),
)
async def get_viewer_package(
    dataset_id: str,
    representation_id: str,
) -> WellMultitrackV1:
    """
    Return the viewer package for the given dataset + representation.

    Full delegation chain:
      1. msi_well_adapter.get_viewer_availability()         — verify MSI lifecycle state
      2. well_viewer_package_service.generate_for_representation() — assemble package
      3. well_qaqc_service.run_qaqc()                       — generate findings
      4. well_qaqc_service.attach_findings_to_package()     — attach findings to package
      5. return package

    WL-BUILD-001: steps 1 and 2 raise NotImplementedError; route converts to HTTP 501.
    The full chain is expressed so no step is silently skipped when earlier
    steps are wired in later sprints.
    """
    try:
        # Step 1 — verify MSI lifecycle state before assembling the package.
        # Raises NotImplementedError in scaffold state.
        _msi_adapter.get_viewer_availability(dataset_id, representation_id)

        # Step 2 — assemble the well_multitrack_v1 viewer package.
        # Raises NotImplementedError in scaffold state.
        pkg = _viewer_package_service.generate_for_representation(
            dataset_id=dataset_id,
            representation_id=representation_id,
        )

        # Step 3 — run QAQC against the assembled package.
        # run_qaqc() returns [] in scaffold state; does not raise.
        findings = _qaqc_service.run_qaqc(pkg)

        # Step 4 — attach findings and return.
        return _qaqc_service.attach_findings_to_package(pkg, findings)

    except NotImplementedError as exc:
        raise _not_implemented_to_501(
            exc,
            "Viewer package not yet available",
        )


# ---------------------------------------------------------------------------
# QAQC findings endpoint
# ---------------------------------------------------------------------------


@router.get(
    "/{dataset_id}/representations/{representation_id}/qaqc",
    response_model=list[QaqcFinding],
    summary="Fetch backend-owned QAQC findings for a representation.",
    description=(
        "Returns QAQC findings generated by the backend QAQC service. "
        "Frontend displays these findings; it must not infer QAQC independently."
    ),
)
async def get_qaqc_findings(
    dataset_id: str,
    representation_id: str,
) -> list[QaqcFinding]:
    """
    Return QAQC findings for the given dataset + representation.

    Full delegation chain:
      1. msi_well_adapter.get_viewer_availability()              — verify MSI state
      2. well_qaqc_service.get_findings_for_representation()     — retrieve findings
      3. return findings

    WL-BUILD-001: steps 1 and 2 raise NotImplementedError; route converts to HTTP 501.
    """
    try:
        # Step 1 — verify MSI lifecycle state.
        # Raises NotImplementedError in scaffold state.
        _msi_adapter.get_viewer_availability(dataset_id, representation_id)

        # Step 2 — retrieve persisted QAQC findings from the MSI-attached artifact.
        # Raises NotImplementedError in scaffold state.
        return _qaqc_service.get_findings_for_representation(
            dataset_id=dataset_id,
            representation_id=representation_id,
        )

    except NotImplementedError as exc:
        raise _not_implemented_to_501(
            exc,
            "QAQC findings not yet available",
        )


# ---------------------------------------------------------------------------
# Well list endpoint
# ---------------------------------------------------------------------------


@router.get(
    "/",
    summary="List available wells (MSI-registered datasets).",
)
async def list_wells() -> list:
    """
    List well datasets registered in MSI.

    Full delegation chain:
      1. msi_well_adapter.list_wells() — query MSI for registered well datasets
      2. return result

    WL-BUILD-001: adapter raises NotImplementedError; route converts to HTTP 501.
    """
    try:
        return _msi_adapter.list_wells()
    except NotImplementedError as exc:
        raise _not_implemented_to_501(
            exc,
            "Well list not yet available",
        )
