export type TransientScreenPoint = Readonly<{ x: number; y: number }>;
export type TransientTrajectoryStation<TPoint> = Readonly<{ point: TPoint; sceneX: number; sceneY: number; sceneZ: number; screenX: number; screenY: number }>;
export type TransientTrajectoryLocation<TPoint> = Readonly<{ point: TPoint; sceneX: number; sceneY: number; sceneZ: number; screenX: number; screenY: number; distancePx: number; segmentIndex: number; ratio: number; arcPosition: number; projectedDistance: number }>;
export type TransientContinuityPolicy = Readonly<{ globalHitTolerancePx: number; localSegmentRadius: number; continuityPenaltyPx: number }>;
export const DEFAULT_TRANSIENT_CONTINUITY_POLICY: TransientContinuityPolicy = Object.freeze({ globalHitTolerancePx: 24, localSegmentRadius: 12, continuityPenaltyPx: 1.25 });
type SegmentProjection = Readonly<{ segmentIndex: number; ratio: number; screenX: number; screenY: number; distancePx: number; projectedDistance: number; score: number }>;
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const lerp=(a:number,b:number,t:number)=>a+(b-a)*t;
export class TransientContinuityController<TPoint>{
 readonly #stations:readonly TransientTrajectoryStation<TPoint>[]; readonly #interpolatePoint:(a:TPoint,b:TPoint,t:number)=>TPoint; readonly #policy:TransientContinuityPolicy; readonly #cum:readonly number[]; #current:SegmentProjection|null=null;
 constructor(stations:readonly TransientTrajectoryStation<TPoint>[], interpolatePoint:(a:TPoint,b:TPoint,t:number)=>TPoint, policy:TransientContinuityPolicy=DEFAULT_TRANSIENT_CONTINUITY_POLICY){ if(stations.length<2) throw new Error('Transient continuity requires at least two trajectory stations.'); this.#stations=stations; this.#interpolatePoint=interpolatePoint; this.#policy=policy; const c=[0]; for(let i=0;i<stations.length-1;i++) c.push(c[i]+Math.hypot(stations[i+1].screenX-stations[i].screenX,stations[i+1].screenY-stations[i].screenY)); this.#cum=c; }
 start(pointer:TransientScreenPoint){ const hit=this.#best(pointer,0,this.#stations.length-2,null); if(!hit||hit.distancePx>this.#policy.globalHitTolerancePx)return null; this.#current=hit; return this.#location(hit); }
 update(pointer:TransientScreenPoint){ if(!this.#current)return this.start(pointer); const min=Math.max(0,this.#current.segmentIndex-this.#policy.localSegmentRadius), max=Math.min(this.#stations.length-2,this.#current.segmentIndex+this.#policy.localSegmentRadius); const hit=this.#best(pointer,min,max,this.#current); if(!hit)return this.#location(this.#current); this.#current=hit; return this.#location(this.#current); }
 locationAtArc(projectedDistance:number){ const max=this.#cum[this.#cum.length-1], d=clamp(projectedDistance,0,max); let i=this.#cum.length-2; for(let n=0;n<this.#cum.length-1;n++){ if(d>=this.#cum[n]&&d<=this.#cum[n+1]){i=n;break;} } const span=Math.max(Number.EPSILON,this.#cum[i+1]-this.#cum[i]), t=clamp((d-this.#cum[i])/span,0,1), a=this.#stations[i], b=this.#stations[i+1]; return this.#location({segmentIndex:i,ratio:t,screenX:lerp(a.screenX,b.screenX,t),screenY:lerp(a.screenY,b.screenY,t),distancePx:0,projectedDistance:d,score:0}); }
 clear(){this.#current=null;}
 #best(pointer:TransientScreenPoint,min:number,max:number,previous:SegmentProjection|null){ let best:SegmentProjection|null=null; for(let i=min;i<=max;i++){ const a=this.#stations[i],b=this.#stations[i+1],dx=b.screenX-a.screenX,dy=b.screenY-a.screenY,l2=dx*dx+dy*dy,t=l2>0?clamp(((pointer.x-a.screenX)*dx+(pointer.y-a.screenY)*dy)/l2,0,1):0,x=lerp(a.screenX,b.screenX,t),y=lerp(a.screenY,b.screenY,t),dist=Math.hypot(pointer.x-x,pointer.y-y),seg=Math.sqrt(l2),pd=this.#cum[i]+seg*t,pen=previous?Math.abs(pd-previous.projectedDistance)*this.#policy.continuityPenaltyPx/100:0,score=dist+pen; if(!best||score<best.score)best={segmentIndex:i,ratio:t,screenX:x,screenY:y,distancePx:dist,projectedDistance:pd,score}; } return best; }
 #location(h:SegmentProjection):TransientTrajectoryLocation<TPoint>{ const a=this.#stations[h.segmentIndex],b=this.#stations[h.segmentIndex+1]; return {point:this.#interpolatePoint(a.point,b.point,h.ratio),sceneX:lerp(a.sceneX,b.sceneX,h.ratio),sceneY:lerp(a.sceneY,b.sceneY,h.ratio),sceneZ:lerp(a.sceneZ,b.sceneZ,h.ratio),screenX:h.screenX,screenY:h.screenY,distancePx:h.distancePx,segmentIndex:h.segmentIndex,ratio:h.ratio,arcPosition:h.projectedDistance,projectedDistance:h.projectedDistance}; }
}
