"""Tests for WLV KR-3 — Definition Import and Staging Contract.

Covers all 20 acceptance criteria from the KR-3 work order:

 1. Valid import preview returns valid=True and staged=False.
 2. Valid import stage creates candidate records.
 3. Staged candidate records do not appear in production-eligible records.
 4. Staged candidate records appear in candidate list / status summary.
 5. Import source creates evidence / source record.
 6. Candidate records include evidence_refs.
 7. Missing source block fails validation (HTTP 422 from Pydantic).
 8. Missing canonical_curve_id fails validation.
 9. Duplicate canonical_curve_id in payload fails validation.
10. Duplicate alias in same payload fails validation.
11. Alias mapped to multiple canonical curve IDs fails validation.
12. Alias conflict with existing seed alias is an error.
13. Display rule referencing unknown canonical_curve_id fails validation.
14. Classification rule with invalid product_group fails validation.
15. Malformed payload returns appropriate error (HTTP 422).
16. KR-1 endpoints still pass.
17. KR-2 managed health / schema / status-summary still pass.
18. Templates remain non-production unless explicitly staged as candidates.
19. No approval / promotion endpoint is added in KR-3.
20. Imported candidates do not affect KR-1 production endpoints.

Additional tests:
- Valid stage response shape matches contract spec.
- Evidence record has correct source fields.
- Staged alias record has correct normalized_alias.
- Staged classification rule has evidence_refs.
- Staged display rule has candidate status.
- Preview is idempotent (calling twice changes nothing).
- Service-level tests use isolated fresh repository instances.
- Import with only display_rules targeting existing seed curves succeeds.
- Import with empty sections is valid (no curve_definitions is ok).
"""

from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from backend.app.main import app
from backend.app.knowledge.api_managed_knowledge import get_managed_repository
from backend.app.knowledge.governance import GovernanceStatus
from backend.app.knowledge.import_models import (
    ImportCurveDefinition,
    ImportClassificationRule,
    ImportDisplayRule,
    ImportPayload,
    ImportSource,
    ImportTemplateRule,
)
from backend.app.knowledge.import_staging_service import stage_import_payload
from backend.app.knowledge.import_validation_service import validate_import_payload
from backend.app.knowledge.managed_models import AliasRecord, CurveDefinitionRecord
from backend.app.knowledge.managed_repository import ManagedKRRepository
from backend.app.knowledge.models import KR_VERSION

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def repo() -> ManagedKRRepository:
    """Fresh isolated ManagedKRRepository for each service-level test."""
    return ManagedKRRepository()


@pytest.fixture
def client_with_repo(repo: ManagedKRRepository) -> TestClient:
    """TestClient wired to an isolated fresh repository via DI override."""
    app.dependency_overrides[get_managed_repository] = lambda: repo
    test_client = TestClient(app)
    yield test_client
    app.dependency_overrides.clear()


@pytest.fixture
def valid_payload() -> ImportPayload:
    """A complete, valid import payload for use in multiple tests."""
    return ImportPayload(
        source=ImportSource(
            source_type="manual_import",
            source_label="KR-3 Test Import Set 001",
            source_reference="test_kr3_reference",
            notes="Generated by KR-3 test suite",
        ),
        curve_definitions=[
            ImportCurveDefinition(
                canonical_curve_id="spectral_gamma_ray",
                display_name="Spectral Gamma Ray",
                family="spectral_gamma_ray",
                product_group="open_hole_logs",
                product_subgroup="gamma_ray",
                default_unit="API",
                description="Spectral gamma ray measurement.",
                aliases=["SGR", "THOR", "URAN", "POTA"],
            )
        ],
        display_rules=[
            ImportDisplayRule(
                canonical_curve_id="spectral_gamma_ray",
                preferred_track_family="gamma_ray_sp",
                scale_type="linear",
                display_min=0.0,
                display_max=300.0,
                default_unit="API",
                reverse_scale=False,
                overlay_group="gamma_ray",
            )
        ],
        classification_rules=[
            ImportClassificationRule(
                rule_key="alias_sgr_to_spectral_gamma_ray",
                match_type="mnemonic_exact",
                match_value="SGR",
                product_group="open_hole_logs",
                product_subgroup="gamma_ray",
                curve_family="spectral_gamma_ray",
                confidence=0.95,
            )
        ],
    )


# ===========================================================================
# 1. Valid import preview returns valid=True and staged=False
# ===========================================================================

class TestImportPreview:
    def test_valid_preview_returns_valid_true(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/preview",
            json=valid_payload.model_dump(),
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["valid"] is True

    def test_valid_preview_staged_is_false(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/preview",
            json=valid_payload.model_dump(),
        )
        data = resp.json()
        assert data["staged"] is False

    def test_valid_preview_mode_is_preview(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/preview",
            json=valid_payload.model_dump(),
        )
        data = resp.json()
        assert data["mode"] == "preview"

    def test_valid_preview_candidate_record_count(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/preview",
            json=valid_payload.model_dump(),
        )
        data = resp.json()
        # 1 curve_def + 4 aliases + 1 display_rule + 1 classification_rule = 7
        assert data["candidate_record_count"] == 7

    def test_valid_preview_error_count_zero(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/preview",
            json=valid_payload.model_dump(),
        )
        data = resp.json()
        assert data["error_count"] == 0
        assert data["errors"] == []

    def test_preview_does_not_add_candidates_to_repo(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        """Preview must be side-effect free."""
        candidates_before = len(repo.list_candidates())
        validate_import_payload(valid_payload, repo)
        candidates_after = len(repo.list_candidates())
        assert candidates_before == candidates_after

    def test_preview_idempotent(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        """Calling preview twice must return identical counts."""
        r1 = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/preview",
            json=valid_payload.model_dump(),
        ).json()
        r2 = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/preview",
            json=valid_payload.model_dump(),
        ).json()
        assert r1["candidate_record_count"] == r2["candidate_record_count"]
        assert r1["valid"] == r2["valid"]


# ===========================================================================
# 2. Valid import stage creates candidate records
# ===========================================================================

class TestImportStage:
    def test_valid_stage_returns_valid_true(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/stage",
            json=valid_payload.model_dump(),
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["valid"] is True

    def test_valid_stage_staged_is_true(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/stage",
            json=valid_payload.model_dump(),
        )
        data = resp.json()
        assert data["staged"] is True

    def test_valid_stage_has_batch_id(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/stage",
            json=valid_payload.model_dump(),
        )
        data = resp.json()
        assert data["import_batch_id"] is not None
        assert data["import_batch_id"].startswith("kr_import_")

    def test_valid_stage_creates_candidate_records(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        candidates_before = len(repo.list_candidates())
        stage_import_payload(valid_payload, repo)
        candidates_after = len(repo.list_candidates())
        # 1 curve_def + 4 aliases + 1 display_rule + 1 classification_rule = 7 new
        assert candidates_after - candidates_before == 7

    def test_valid_stage_record_ids_returned(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/stage",
            json=valid_payload.model_dump(),
        )
        data = resp.json()
        assert isinstance(data["record_ids"], list)
        assert len(data["record_ids"]) == 7

    def test_valid_stage_mode_is_stage(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/stage",
            json=valid_payload.model_dump(),
        )
        assert resp.json()["mode"] == "stage"

    def test_valid_stage_record_type_counts(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/stage",
            json=valid_payload.model_dump(),
        )
        counts = resp.json()["record_type_counts"]
        assert counts["curve_definition"] == 1
        assert counts["alias"] == 4
        assert counts["display_rule"] == 1
        assert counts["classification_rule"] == 1
        assert counts["template_rule"] == 0
        assert counts["evidence"] == 1


# ===========================================================================
# 3. Staged candidate records do not appear in production-eligible records
# ===========================================================================

class TestCandidateNonProduction:
    def test_staged_candidates_not_in_production_eligible(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        staging = stage_import_payload(valid_payload, repo)
        staged_ids = set(staging.record_ids)
        production = repo.list_production_eligible()
        production_ids = {r.record_id for r in production}
        assert staged_ids.isdisjoint(production_ids), (
            f"Staged candidate IDs appeared in production-eligible list: "
            f"{staged_ids & production_ids}"
        )

    def test_staged_candidates_not_in_list_approved(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        staging = stage_import_payload(valid_payload, repo)
        staged_ids = set(staging.record_ids)
        approved = repo.list_approved()
        approved_ids = {r.record_id for r in approved}
        assert staged_ids.isdisjoint(approved_ids)

    def test_staged_candidates_not_in_list_seeds(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        stage_import_payload(valid_payload, repo)
        seeds = repo.list_seeds()
        seed_ids = {r.record_id for r in seeds}
        assert not any(rid.startswith("import_") for rid in seed_ids)

    def test_staged_curve_def_status_is_candidate(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        staging = stage_import_payload(valid_payload, repo)
        for rid in staging.record_ids:
            record = repo.get_by_id(rid)
            assert record is not None
            assert record.status == GovernanceStatus.CANDIDATE, (
                f"Record {rid} has status {record.status}, expected CANDIDATE"
            )


# ===========================================================================
# 4. Staged candidate records appear in candidate list / status summary
# ===========================================================================

class TestCandidateVisibility:
    def test_staged_candidates_appear_in_list_candidates(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        staging = stage_import_payload(valid_payload, repo)
        staged_ids = set(staging.record_ids)
        candidates = repo.list_candidates()
        candidate_ids = {r.record_id for r in candidates}
        assert staged_ids.issubset(candidate_ids)

    def test_staged_candidates_increase_status_summary_candidate_count(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        before = repo.get_status_summary()["candidate"]
        stage_import_payload(valid_payload, repo)
        after = repo.get_status_summary()["candidate"]
        assert after > before

    def test_status_summary_endpoint_reflects_staged_candidates(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        before_resp = client_with_repo.get("/api/wlv/knowledge/managed/status-summary")
        before_count = before_resp.json()["candidate_count"]

        client_with_repo.post(
            "/api/wlv/knowledge/managed/import/stage",
            json=valid_payload.model_dump(),
        )

        after_resp = client_with_repo.get("/api/wlv/knowledge/managed/status-summary")
        after_count = after_resp.json()["candidate_count"]
        assert after_count > before_count


# ===========================================================================
# 5. Import source creates evidence / source record
# ===========================================================================

class TestEvidenceRecord:
    def test_stage_creates_evidence_record(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        evidence_before = len(repo.list_evidence())
        stage_import_payload(valid_payload, repo)
        evidence_after = len(repo.list_evidence())
        assert evidence_after == evidence_before + 1

    def test_evidence_record_source_type_matches(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        staging = stage_import_payload(valid_payload, repo)
        evidence_id = f"import_evidence_{staging.import_batch_id}"
        ev = repo.get_evidence_by_id(evidence_id)
        assert ev is not None
        assert ev.source_type == valid_payload.source.source_type

    def test_evidence_record_source_label_matches(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        staging = stage_import_payload(valid_payload, repo)
        evidence_id = f"import_evidence_{staging.import_batch_id}"
        ev = repo.get_evidence_by_id(evidence_id)
        assert ev is not None
        assert ev.source_label == valid_payload.source.source_label

    def test_evidence_record_has_source_reference(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        staging = stage_import_payload(valid_payload, repo)
        evidence_id = f"import_evidence_{staging.import_batch_id}"
        ev = repo.get_evidence_by_id(evidence_id)
        assert ev is not None
        assert ev.source_reference == valid_payload.source.source_reference

    def test_evidence_record_count_in_staging_result(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        staging = stage_import_payload(valid_payload, repo)
        assert staging.evidence_record_count == 1


# ===========================================================================
# 6. Candidate records include evidence_refs
# ===========================================================================

class TestEvidenceRefs:
    def test_staged_curve_def_has_evidence_refs(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        staging = stage_import_payload(valid_payload, repo)
        expected_ev_id = f"import_evidence_{staging.import_batch_id}"
        for rid in staging.record_ids:
            record = repo.get_by_id(rid)
            assert record is not None
            refs = getattr(record, "evidence_refs", [])
            assert expected_ev_id in refs, (
                f"Record {rid} missing evidence_ref '{expected_ev_id}': {refs}"
            )

    def test_staged_alias_has_evidence_refs(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        staging = stage_import_payload(valid_payload, repo)
        expected_ev_id = f"import_evidence_{staging.import_batch_id}"
        aliases = [
            r for r in repo.list_candidates()
            if r.record_type == "alias" and r.record_id.startswith("import_")
        ]
        assert aliases, "No staged alias candidates found"
        for alias_rec in aliases:
            assert expected_ev_id in alias_rec.evidence_refs


# ===========================================================================
# 7. Missing source block fails validation (HTTP 422 from Pydantic)
# ===========================================================================

class TestMissingSourceBlock:
    def test_missing_source_block_preview_returns_422(
        self, client_with_repo: TestClient
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/preview",
            json={"curve_definitions": []},
        )
        # Pydantic rejects missing required 'source' field with 422
        assert resp.status_code == 422

    def test_missing_source_block_stage_returns_422(
        self, client_with_repo: TestClient
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/stage",
            json={"curve_definitions": []},
        )
        assert resp.status_code == 422

    def test_empty_source_type_fails_validation(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="", source_label="Test"),
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        assert any(
            "source_type" in e.path for e in result.errors
        ), "Expected error on source.source_type"

    def test_empty_source_label_fails_validation(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label=""),
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        assert any(
            "source_label" in e.path for e in result.errors
        ), "Expected error on source.source_label"


# ===========================================================================
# 8. Missing canonical_curve_id fails validation
# ===========================================================================

class TestMissingCanonicalCurveId:
    def test_missing_canonical_curve_id_fails(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="",
                    display_name="Test Curve",
                    family="test_family",
                    product_group="open_hole_logs",
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        error_paths = [e.path for e in result.errors]
        assert any("canonical_curve_id" in p for p in error_paths)

    def test_missing_canonical_curve_id_error_code(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="",
                    display_name="Test",
                    family="test",
                    product_group="open_hole_logs",
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert any(e.code == "missing_required_field" for e in result.errors)

    def test_missing_display_name_fails(self, repo: ManagedKRRepository) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="test_curve",
                    display_name="",
                    family="test_family",
                    product_group="open_hole_logs",
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        assert any("display_name" in e.path for e in result.errors)

    def test_missing_family_fails(self, repo: ManagedKRRepository) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="test_curve",
                    display_name="Test",
                    family="",
                    product_group="open_hole_logs",
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        assert any("family" in e.path for e in result.errors)

    def test_missing_product_group_fails(self, repo: ManagedKRRepository) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="test_curve",
                    display_name="Test",
                    family="test_family",
                    product_group="",
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        assert any("product_group" in e.path for e in result.errors)


# ===========================================================================
# 9. Duplicate canonical_curve_id in payload fails validation
# ===========================================================================

class TestDuplicateCanonicalCurveId:
    def test_duplicate_canonical_curve_id_fails(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="duplicate_curve",
                    display_name="Duplicate A",
                    family="test_family",
                    product_group="open_hole_logs",
                ),
                ImportCurveDefinition(
                    canonical_curve_id="duplicate_curve",
                    display_name="Duplicate B",
                    family="test_family",
                    product_group="open_hole_logs",
                ),
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        dup_errors = [e for e in result.errors if e.code == "duplicate_canonical_curve_id"]
        assert len(dup_errors) >= 1

    def test_duplicate_canonical_curve_id_error_path(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="dup_id",
                    display_name="A",
                    family="f",
                    product_group="open_hole_logs",
                ),
                ImportCurveDefinition(
                    canonical_curve_id="dup_id",
                    display_name="B",
                    family="f",
                    product_group="open_hole_logs",
                ),
            ],
        )
        result = validate_import_payload(payload, repo)
        dup_errors = [e for e in result.errors if e.code == "duplicate_canonical_curve_id"]
        assert dup_errors[0].path.startswith("curve_definitions[1]")


# ===========================================================================
# 10. Duplicate alias in same payload fails validation
# ===========================================================================

class TestDuplicateAlias:
    def test_duplicate_alias_within_curve_definition_fails(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="test_curve",
                    display_name="Test",
                    family="test_family",
                    product_group="open_hole_logs",
                    aliases=["GR", "GR"],  # duplicate
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        dup_alias_errors = [
            e for e in result.errors if e.code == "duplicate_alias_in_curve_definition"
        ]
        assert len(dup_alias_errors) >= 1

    def test_duplicate_alias_case_insensitive(
        self, repo: ManagedKRRepository
    ) -> None:
        """'GR' and 'gr' normalize to the same alias."""
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="test_curve",
                    display_name="Test",
                    family="test_family",
                    product_group="open_hole_logs",
                    aliases=["GR", "gr"],
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid


# ===========================================================================
# 11. Alias mapped to multiple canonical curve IDs fails validation
# ===========================================================================

class TestAliasMultipleCanonicalIds:
    def test_alias_mapped_to_two_canonical_ids_fails(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="curve_a",
                    display_name="Curve A",
                    family="family_a",
                    product_group="open_hole_logs",
                    aliases=["SHARED_ALIAS"],
                ),
                ImportCurveDefinition(
                    canonical_curve_id="curve_b",
                    display_name="Curve B",
                    family="family_b",
                    product_group="open_hole_logs",
                    aliases=["SHARED_ALIAS"],
                ),
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        multi_errors = [
            e for e in result.errors
            if e.code == "alias_mapped_to_multiple_canonical_ids"
        ]
        assert len(multi_errors) >= 1

    def test_alias_multi_id_error_path(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="alpha",
                    display_name="Alpha",
                    family="f",
                    product_group="open_hole_logs",
                    aliases=["CONFLICT"],
                ),
                ImportCurveDefinition(
                    canonical_curve_id="beta",
                    display_name="Beta",
                    family="f",
                    product_group="open_hole_logs",
                    aliases=["CONFLICT"],
                ),
            ],
        )
        result = validate_import_payload(payload, repo)
        multi_errors = [
            e for e in result.errors
            if e.code == "alias_mapped_to_multiple_canonical_ids"
        ]
        assert multi_errors[0].path.startswith("curve_definitions[1]")


# ===========================================================================
# 12. Alias conflict with existing seed alias is an error (or warning for same curve)
# ===========================================================================

class TestAliasConflictWithSeedRecords:
    def test_alias_conflict_with_existing_seed_alias_is_error(
        self, repo: ManagedKRRepository
    ) -> None:
        """'GR' maps to 'gamma_ray' in seed; importing it to a different curve is an error."""
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="different_curve",
                    display_name="Different Curve",
                    family="different_family",
                    product_group="open_hole_logs",
                    aliases=["GR"],  # GR already maps to gamma_ray in seed
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        conflict_errors = [
            e for e in result.errors if e.code == "alias_conflicts_with_existing_record"
        ]
        assert len(conflict_errors) >= 1

    def test_alias_conflict_message_includes_existing_canonical_id(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="new_curve",
                    display_name="New Curve",
                    family="new_family",
                    product_group="open_hole_logs",
                    aliases=["GR"],
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        conflict_errors = [
            e for e in result.errors if e.code == "alias_conflicts_with_existing_record"
        ]
        assert any("gamma_ray" in e.message for e in conflict_errors)

    def test_alias_same_canonical_id_as_seed_is_warning_not_error(
        self, repo: ManagedKRRepository
    ) -> None:
        """Importing 'GR' → gamma_ray (same as seed) should warn, not error."""
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="gamma_ray",
                    display_name="Gamma Ray Extended",
                    family="gamma_ray",
                    product_group="open_hole_logs",
                    aliases=["GR"],  # same canonical_curve_id as seed
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        # Should be valid (no errors); may have warning about duplicate alias
        alias_errors = [
            e for e in result.errors if e.code == "alias_conflicts_with_existing_record"
        ]
        assert len(alias_errors) == 0, (
            "Alias conflict to SAME canonical_curve_id should not be an error"
        )


# ===========================================================================
# 13. Display rule referencing unknown canonical_curve_id fails validation
# ===========================================================================

class TestDisplayRuleUnknownCanonicalId:
    def test_display_rule_unknown_curve_id_fails(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            display_rules=[
                ImportDisplayRule(
                    canonical_curve_id="nonexistent_curve_xyz",
                    preferred_track_family="gamma_ray_sp",
                    scale_type="linear",
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        unknown_errors = [
            e for e in result.errors
            if e.code == "display_rule_unknown_canonical_curve_id"
        ]
        assert len(unknown_errors) >= 1

    def test_display_rule_known_seed_curve_id_is_valid(
        self, repo: ManagedKRRepository
    ) -> None:
        """A display rule for an existing seed curve is valid."""
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            display_rules=[
                ImportDisplayRule(
                    canonical_curve_id="gamma_ray",  # exists in seed
                    preferred_track_family="gamma_ray_sp",
                    scale_type="linear",
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        unknown_errors = [
            e for e in result.errors
            if e.code == "display_rule_unknown_canonical_curve_id"
        ]
        assert len(unknown_errors) == 0

    def test_display_rule_curve_id_defined_in_payload_is_valid(
        self, repo: ManagedKRRepository
    ) -> None:
        """A display rule for a curve defined in the SAME payload is valid."""
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="new_payload_curve",
                    display_name="New Payload Curve",
                    family="test_family",
                    product_group="open_hole_logs",
                )
            ],
            display_rules=[
                ImportDisplayRule(
                    canonical_curve_id="new_payload_curve",  # defined in same payload
                    preferred_track_family="gamma_ray_sp",
                    scale_type="linear",
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        unknown_errors = [
            e for e in result.errors
            if e.code == "display_rule_unknown_canonical_curve_id"
        ]
        assert len(unknown_errors) == 0

    def test_display_rule_invalid_scale_type_fails(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            display_rules=[
                ImportDisplayRule(
                    canonical_curve_id="gamma_ray",
                    preferred_track_family="gamma_ray_sp",
                    scale_type="bilinear",  # invalid
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        assert any(e.code == "invalid_scale_type" for e in result.errors)


# ===========================================================================
# 14. Classification rule with invalid product_group / subgroup fails
# ===========================================================================

class TestClassificationRuleValidation:
    def test_invalid_product_group_fails(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            classification_rules=[
                ImportClassificationRule(
                    rule_key="test_rule",
                    match_type="mnemonic_exact",
                    match_value="XYZ",
                    product_group="completely_unknown_group",
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        assert any(e.code == "unknown_product_group" for e in result.errors)

    def test_invalid_product_subgroup_fails(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            classification_rules=[
                ImportClassificationRule(
                    rule_key="test_rule",
                    match_type="mnemonic_exact",
                    match_value="XYZ",
                    product_group="open_hole_logs",
                    product_subgroup="completely_invalid_subgroup",
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid
        assert any(e.code == "unknown_product_subgroup" for e in result.errors)

    def test_valid_product_group_and_subgroup_passes(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            classification_rules=[
                ImportClassificationRule(
                    rule_key="test_rule",
                    match_type="mnemonic_exact",
                    match_value="XYZ",
                    product_group="open_hole_logs",
                    product_subgroup="gamma_ray",
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert result.valid, f"Expected valid but got errors: {result.errors}"


# ===========================================================================
# 15. Malformed payload returns appropriate error (HTTP 422)
# ===========================================================================

class TestMalformedPayload:
    def test_non_json_body_preview_returns_422(
        self, client_with_repo: TestClient
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/preview",
            content=b"not json at all !!!",
            headers={"Content-Type": "application/json"},
        )
        assert resp.status_code == 422

    def test_non_json_body_stage_returns_422(
        self, client_with_repo: TestClient
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/stage",
            content=b"not json at all !!!",
            headers={"Content-Type": "application/json"},
        )
        assert resp.status_code == 422

    def test_empty_object_returns_422(
        self, client_with_repo: TestClient
    ) -> None:
        """Empty JSON object {} is missing required 'source' — FastAPI returns 422."""
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/preview",
            json={},
        )
        assert resp.status_code == 422


# ===========================================================================
# 16. KR-1 endpoints still pass
# ===========================================================================

# Use a standard client (NOT the isolated client) to test the real app state.
_standard_client = TestClient(app)


class TestKR1Compatibility:
    def test_kr1_health_still_200(self) -> None:
        resp = _standard_client.get("/api/wlv/knowledge/health")
        assert resp.status_code == 200

    def test_kr1_health_service_field(self) -> None:
        data = _standard_client.get("/api/wlv/knowledge/health").json()
        assert data["service"] == "wlv_knowledge_repository"
        assert data["status"] == "ok"
        assert data["version"] == KR_VERSION

    def test_kr1_product_groups_still_200(self) -> None:
        resp = _standard_client.get("/api/wlv/knowledge/product-groups")
        assert resp.status_code == 200
        data = resp.json()
        assert len(data["groups"]) == 8

    def test_kr1_curve_definitions_still_200(self) -> None:
        resp = _standard_client.get("/api/wlv/knowledge/curve-definitions")
        assert resp.status_code == 200
        data = resp.json()
        assert len(data["curve_definitions"]) >= 10

    def test_kr1_display_rules_still_200(self) -> None:
        resp = _standard_client.get("/api/wlv/knowledge/display-rules")
        assert resp.status_code == 200

    def test_kr1_templates_still_200_and_empty(self) -> None:
        resp = _standard_client.get("/api/wlv/knowledge/templates")
        assert resp.status_code == 200
        assert resp.json()["templates"] == []


# ===========================================================================
# 17. KR-2 managed endpoints still pass
# ===========================================================================

class TestKR2Compatibility:
    def test_managed_health_still_200(self) -> None:
        resp = _standard_client.get("/api/wlv/knowledge/managed/health")
        assert resp.status_code == 200

    def test_managed_health_fields_intact(self) -> None:
        data = _standard_client.get("/api/wlv/knowledge/managed/health").json()
        assert data["service"] == "wlv_managed_knowledge_repository"
        assert data["status"] == "ok"
        assert data["kr_version"] == "kr-2"

    def test_managed_schema_still_200(self) -> None:
        resp = _standard_client.get("/api/wlv/knowledge/managed/schema")
        assert resp.status_code == 200

    def test_managed_schema_record_types_intact(self) -> None:
        data = _standard_client.get("/api/wlv/knowledge/managed/schema").json()
        rt_keys = {rt["record_type"] for rt in data["record_types"]}
        expected = {
            "curve_definition", "alias", "display_rule",
            "classification_rule", "template_rule", "evidence",
        }
        assert expected == rt_keys

    def test_managed_status_summary_still_200(self) -> None:
        resp = _standard_client.get("/api/wlv/knowledge/managed/status-summary")
        assert resp.status_code == 200

    def test_managed_status_summary_fields_intact(self) -> None:
        data = _standard_client.get("/api/wlv/knowledge/managed/status-summary").json()
        assert data["kr_version"] == "kr-2"
        assert data["total_governed_records"] > 0
        assert data["production_eligible_count"] > 0
        assert data["seed_count"] > 0
        assert "status_by_type" in data


# ===========================================================================
# 18. Templates remain non-production unless explicitly staged
# ===========================================================================

class TestTemplatesNonProduction:
    def test_seed_layer_has_no_template_rule_records(
        self, repo: ManagedKRRepository
    ) -> None:
        template_rules = repo.list_records("template_rule")
        assert template_rules == []

    def test_staged_template_rule_is_candidate_not_production(
        self, repo: ManagedKRRepository
    ) -> None:
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            template_rules=[
                ImportTemplateRule(
                    template_key="test_template",
                    template_label="Test Template",
                )
            ],
        )
        staging = stage_import_payload(payload, repo)
        template_id = f"import_{staging.import_batch_id}_template_test_template"
        record = repo.get_by_id(template_id)
        assert record is not None
        assert record.status == GovernanceStatus.CANDIDATE

        production = repo.list_production_eligible()
        production_ids = {r.record_id for r in production}
        assert template_id not in production_ids


# ===========================================================================
# 19. No approval / promotion endpoint added in KR-3
# ===========================================================================

class TestNoApprovalEndpoint:
    def test_no_approve_endpoint_exists(self) -> None:
        """KR-3 added no approval/promotion endpoints.

        KR-4 has since added /records/{record_id}/approve, /reject, /deprecate
        under the managed namespace — those are intentional and permitted.
        This test now verifies only that no *import*-route-level approval
        endpoints were added by KR-3 (i.e. no /import/approve path).
        """
        from fastapi.routing import APIRoute
        routes = [
            route.path
            for route in app.routes
            if isinstance(route, APIRoute)
        ]

        # These terms must not appear in import-layer paths.
        # KR-4 record management paths (/records/.../approve etc.) are allowed.
        forbidden_import_route_terms = {
            "approval",
            "promote",
        }

        forbidden_routes = []
        for route_path in routes:
            # Skip KR-4 record governance paths — they intentionally have
            # "approve", "reject", "deprecate" as path segments.
            if "/records/" in route_path:
                continue
            path_parts = {
                part.strip().lower()
                for part in route_path.split("/")
                if part.strip()
            }
            if path_parts.intersection(forbidden_import_route_terms):
                forbidden_routes.append(route_path)

        assert forbidden_routes == [], (
            f"Unexpected approval/promotion endpoints found in import routes: {forbidden_routes}"
        )

    def test_no_approval_endpoint_via_http_404(
        self, client_with_repo: TestClient
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/approve",
            json={},
        )
        assert resp.status_code == 404

    def test_no_promote_endpoint_via_http_404(
        self, client_with_repo: TestClient
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/promote",
            json={},
        )
        assert resp.status_code == 404


# ===========================================================================
# 20. Imported candidates do not affect KR-1 production endpoints
# ===========================================================================

class TestCandidatesDoNotAffectKR1:
    def test_staging_does_not_add_to_kr1_curve_definitions(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        from backend.app.knowledge.repository import KnowledgeRepository
        kr1_repo = KnowledgeRepository()
        curve_defs_before = len(kr1_repo.get_curve_definitions().curve_definitions)
        stage_import_payload(valid_payload, repo)
        curve_defs_after = len(kr1_repo.get_curve_definitions().curve_definitions)
        assert curve_defs_before == curve_defs_after, (
            "KR-1 curve definitions should be unaffected by KR-3 staging"
        )

    def test_kr1_curve_definitions_endpoint_count_stable(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        before = _standard_client.get("/api/wlv/knowledge/curve-definitions").json()
        before_count = len(before["curve_definitions"])

        # Stage using the isolated client (which uses a separate repo)
        client_with_repo.post(
            "/api/wlv/knowledge/managed/import/stage",
            json=valid_payload.model_dump(),
        )

        after = _standard_client.get("/api/wlv/knowledge/curve-definitions").json()
        after_count = len(after["curve_definitions"])
        assert before_count == after_count

    def test_production_eligible_records_have_no_import_prefix_after_staging(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        stage_import_payload(valid_payload, repo)
        production = repo.list_production_eligible()
        production_ids = [r.record_id for r in production]
        import_prefixed = [rid for rid in production_ids if rid.startswith("import_")]
        assert import_prefixed == [], (
            f"Import-prefixed IDs found in production-eligible: {import_prefixed}"
        )


# ===========================================================================
# Additional service-level tests
# ===========================================================================

class TestServiceLevel:
    def test_valid_payload_with_no_optional_sections(
        self, repo: ManagedKRRepository
    ) -> None:
        """A payload with only source and no definitions sections is valid."""
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Minimal Test"),
        )
        result = validate_import_payload(payload, repo)
        assert result.valid
        assert result.candidate_record_count == 0
        assert result.evidence_record_count == 1

    def test_staging_deterministic_batch_id(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        """Passing a fixed batch_id produces deterministic record IDs."""
        staging = stage_import_payload(valid_payload, repo, batch_id="kr_import_testbatch")
        assert staging.import_batch_id == "kr_import_testbatch"
        expected_curve_id = "import_kr_import_testbatch_curve_def_spectral_gamma_ray"
        assert expected_curve_id in staging.record_ids

    def test_staged_alias_normalized_correctly(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        stage_import_payload(valid_payload, repo)
        aliases = [
            r for r in repo.list_candidates()
            if r.record_type == "alias" and r.record_id.startswith("import_")
        ]
        normalized_aliases = [r.normalized_alias for r in aliases]  # type: ignore[union-attr]
        assert "SGR" in normalized_aliases
        assert "THOR" in normalized_aliases
        assert "URAN" in normalized_aliases
        assert "POTA" in normalized_aliases

    def test_staged_classification_rule_has_correct_product_group(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        staging = stage_import_payload(valid_payload, repo)
        class_rule_ids = [r for r in staging.record_ids if "_class_" in r]
        assert class_rule_ids, "No classification rule records staged"
        rule = repo.get_by_id(class_rule_ids[0])
        assert rule is not None
        assert rule.product_group == "open_hole_logs"  # type: ignore[union-attr]

    def test_staged_display_rule_has_candidate_status(
        self, repo: ManagedKRRepository, valid_payload: ImportPayload
    ) -> None:
        staging = stage_import_payload(valid_payload, repo)
        display_ids = [r for r in staging.record_ids if "_display_" in r]
        assert display_ids
        dr = repo.get_by_id(display_ids[0])
        assert dr is not None
        assert dr.status == GovernanceStatus.CANDIDATE

    def test_preview_response_has_kr_version(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/preview",
            json=valid_payload.model_dump(),
        )
        data = resp.json()
        assert "kr_version" in data
        assert data["kr_version"] == "kr-3"

    def test_stage_response_has_kr_version(
        self, client_with_repo: TestClient, valid_payload: ImportPayload
    ) -> None:
        resp = client_with_repo.post(
            "/api/wlv/knowledge/managed/import/stage",
            json=valid_payload.model_dump(),
        )
        data = resp.json()
        assert "kr_version" in data
        assert data["kr_version"] == "kr-3"

    def test_invalid_stage_does_not_mutate_repo(
        self, repo: ManagedKRRepository
    ) -> None:
        """A failed validation must not add any records."""
        payload = ImportPayload(
            source=ImportSource(source_type="manual_import", source_label="Test"),
            curve_definitions=[
                ImportCurveDefinition(
                    canonical_curve_id="",  # invalid
                    display_name="Test",
                    family="test",
                    product_group="open_hole_logs",
                )
            ],
        )
        result = validate_import_payload(payload, repo)
        assert not result.valid

        before_count = len(repo.list_candidates())
        # Even if caller mistakenly calls stage on invalid payload,
        # validation should block it from an HTTP perspective.
        # At service level, stage_import_payload doesn't validate itself,
        # so this test just verifies the validate step is used before staging.
        assert before_count == 0  # fresh repo has no candidates
