/**
 * Frontend TypeScript types for the shared canvas session API.
 *
 * These mirror the backend `ResolvedWdvCanvasSession` and related DTOs
 * (snake_case, as returned by the JSON response).  The presentation
 * adapter converts them to camelCase WellLogTrack structures consumed
 * by the WDV renderer.
 *
 * These types are read-only API response shapes and must never be
 * mutated or persisted by the frontend.
 */

export type SharedCanvasBindingStatus =
  | 'bound'
  | 'unavailable'
  | 'unresolved'
  | 'excluded'
  | 'incompatible'
  | 'user_unbound'
  | 'stale_binding';

export interface SharedCanvasResolvedSlot {
  slot_uid: string;
  slot_key: string;
  slot_order: number;
  binding_status: SharedCanvasBindingStatus;
  /** Non-null only when binding_status === 'bound'. */
  managed_curve_uid: string | null;
  display_name: string | null;
  mnemonic: string | null;
  curve_family: string | null;
  kr_curve_type_id: string | null;
  unit: string | null;
  /** Numeric scale value for plotting; retained verbatim. */
  scale_min: number | null;
  /** Numeric scale value for plotting; retained verbatim. */
  scale_max: number | null;
  /** Display label generated by the backend formatter; for headers only. */
  scale_min_label: string | null;
  /** Display label generated by the backend formatter; for headers only. */
  scale_max_label: string | null;
  warnings: string[];
}

export interface SharedCanvasResolvedTrack {
  track_uid: string;
  track_key: string | null;
  track_order: number;
  track_name: string;
  track_type: string;
  track_role: string | null;
  renderer_type: string | null;
  width_px: number | null;
  lattice: string | null;
  lattice_source: string | null;
  scale_mode: string;
  depth_basis: string | null;
  slots: SharedCanvasResolvedSlot[];
}

export interface SharedCanvasBindingSummary {
  total_slots: number;
  bound: number;
  unavailable: number;
  unresolved: number;
  excluded: number;
  incompatible: number;
  user_unbound: number;
  stale_binding: number;
}

/**
 * Resolved shared canvas session for one well against an active profile revision.
 *
 * Produced per-request by the backend; never persisted by the frontend.
 * Contains depth_min/max/unit for the well's depth viewport.
 */
export interface ResolvedWdvCanvasSession {
  managed_well_uid: string;
  profile_uid: string;
  profile_revision_uid: string;
  profile_revision_number: number;
  activation_scope_type: string;
  activation_scope_uid: string;
  resolved_tracks: SharedCanvasResolvedTrack[];
  binding_summary: SharedCanvasBindingSummary;
  warnings: string[];
  updated_at: string;
  /** Well depth minimum in depth_unit. */
  depth_min: number;
  /** Well depth maximum in depth_unit. */
  depth_max: number;
  /** Depth unit string (e.g. 'ft' or 'm'). */
  depth_unit: string;
}
